### PR TITLE
change to PHS

### PR DESCRIPTION
**Pull request by alan-y**
Changes required for change to phstemplates package.
Also some other minor changes (mainly so that devtools::check() doesn't leave any notes).
The only mention of PHI remaining is to the PHI R Style guide.

@jackhannah95 - any changes required for Travis?

### CODE REVIEW

**Comment by jackhannah95** [comment]
Looks good to me 👍 The only thing I've spotted is the `phiproject.Rproj` file which can be deleted. It's fine to leave the reference to the style guide there - TPP may (or may not) do a big re-brand of stuff like that in the future. Travis should adjust to the name change on its own I think, but if not I can take a look once this branch is merged.

**Comment by alan-y** [comment]
> The only thing I've spotted is the `phiproject.Rproj` file which can be deleted.

Thanks and nice spot - should be deleted now.

**Comment by alan-y** [comment]
> Hi Alan, almost everything looks good except that I spotted one thing that looked off. This was in the non-1.2 report where the spacing in an area looked off.

I've checked this loads fine for me... although you have helped me to spot that I've not applied other updates to the non-1.2 version of the HPS template - no worries as don't think many people will use the non-1.2 version and I'll be thinking of getting rid of it in future...

**Comment by RoryMadigan** [comment]
Thanks for that Jack!

**Pull request merged**
